# Generated by Django 2.1.3 on 2019-04-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.IntegerField(default=0)),
                ('registration_number', models.IntegerField(default=0)),
                ('roll_number', models.IntegerField(default=0)),
                ('admission_year', models.IntegerField(default=0)),
                ('current_semester', models.IntegerField(default=0)),
                ('current_section', models.CharField(max_length=2)),
            ],
        ),
    ]
