# Generated by Django 2.1.3 on 2019-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField(default=None)),
                ('gender', models.CharField(max_length=2)),
                ('name_mother', models.CharField(max_length=100)),
                ('name_father', models.CharField(max_length=100)),
                ('name_guardian', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
