# Generated by Django 2.1.3 on 2019-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_personaldetails_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='DOB',
            field=models.DateField(),
        ),
    ]
