# Generated by Django 2.1.3 on 2019-04-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_personaldetails_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='enrollment_number',
            field=models.IntegerField(default=0),
        ),
    ]
