# Generated by Django 2.1.3 on 2019-04-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='mobile_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='pin_code',
            field=models.IntegerField(),
        ),
    ]
