# Generated by Django 2.1.3 on 2019-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190409_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.IntegerField(default=0)),
                ('stream_id', models.IntegerField(default=0)),
                ('course_id', models.CharField(max_length=10)),
                ('tenth_school_name', models.CharField(max_length=10)),
                ('tenth_board_percentage', models.FloatField(default=0.0)),
                ('tenth_year_of_passing', models.IntegerField()),
                ('tenth_board_name', models.CharField(max_length=50)),
                ('twelfth_school_name', models.CharField(max_length=10)),
                ('twelfth_board_percentage', models.FloatField(default=0.0)),
                ('twelfth_year_of_passing', models.IntegerField()),
                ('twelfth_board_name', models.CharField(max_length=50)),
            ],
        ),
    ]
