# Generated by Django 2.1.3 on 2019-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_academicdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdetails',
            name='stream_id',
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='course_id',
            field=models.CharField(default='CS101', max_length=10),
        ),
    ]
