# Generated by Django 2.1.3 on 2019-04-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20190410_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.IntegerField(default=0)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=3)),
            ],
        ),
    ]
