# Generated by Django 2.1.3 on 2019-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
            ],
        ),
    ]
