# Generated by Django 2.1.3 on 2019-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.IntegerField(default=0)),
                ('test_url', models.URLField(max_length=100)),
                ('result_url', models.URLField(max_length=100)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
