# Generated by Django 2.1.3 on 2019-04-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20190417_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='UEMCRP Test', max_length=50),
        ),
    ]
