# Generated by Django 2.1.3 on 2019-04-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_test_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='result_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_url',
            field=models.URLField(max_length=1000),
        ),
    ]
